name: game_15
description: Game-15

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.1
  flutter_hooks: ^0.18.2
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  line_awesome_flutter: ^2.0.0
  provider: ^6.0.2
  utopia_hooks: ^0.2.5+2
  utopia_widgets: ^0.0.9
  flutter_svg: ^1.0.3
  equatable: ^2.0.3
  camera: ^0.9.4+14
  permission_handler: ^9.2.0
  matrix_gesture_detector: ^0.2.0-nullsafety.1
  functional_listener: ^2.1.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/
  fonts:
    - family: "Ugly Byte"
      fonts:
        - asset: fonts/Ugly-Byte.ttf
          weight: 300

  uses-material-design: true

